# This docker-compose file is intended to build the production environments
version: '3'

volumes:
  node_modules:

services:
  db:
    build:
      context: db
    image: pa_db:production
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - ./db/docker_volume/lib/sql/lib:/var/lib/mysql
      - ./db/backups:/backups

  api:
    build:
      context: api
      dockerfile: prod-build.Dockerfile
    environment:
      NODE_ENV: "production"
    image: pa_api:production
    depends_on:
      - db

  web:
    build:
      context: web
      dockerfile: prod-build.Dockerfile
    image: pa_web:production
    environment:
      NODE_ENV: "production"

  proxy:
    build: 
      context: proxy
      args:
        - NGINX_CONFIG=prod      # Change this fallow to "prod" to start using certificates
    image: pa_proxy:production
    ports:
      - "80:80"
    depends_on:
      - api
      - web 