version: '3'
services:

  db:
    image: "mysql:5.7.21"
    ports:
      # Only allow this port to be public in development mode
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
  api:
    build:
      context: api
    image: pa_api
    volumes:
      - ./api:/server
    ports:
      - "3000:3000"
    depends_on:
      - db

  # TODO:
  # - Add compose support for api
  # - Add compose support for web